import {
  ClassicBall,
  Pokeball,
  Greatball,
  Ultraball,
  Luxuryball,
  Premierball,
  Healball,
  Nestball,
  Netball,
  Quickball,
  InfiniteBall,
} from "../components/Icons.jsx";

export const HOME_MODE_CATALOG = [
  {
    id: "classic",
    titleKey: "home.modes.classic.title",
    descKey: "home.modes.classic.desc",
    color: "bg-purple-600",
    Icon: ClassicBall,
  },
  {
    id: "gen1",
    titleKey: "home.modes.gen1.title",
    descKey: "home.modes.gen1.desc",
    color: "bg-red-500",
    Icon: Pokeball,
  },
  {
    id: "gen2",
    titleKey: "home.modes.gen2.title",
    descKey: "home.modes.gen2.desc",
    color: "bg-blue-600",
    Icon: Greatball,
  },
  {
    id: "gen3",
    titleKey: "home.modes.gen3.title",
    descKey: "home.modes.gen3.desc",
    color: "bg-zinc-800",
    Icon: Ultraball,
  },
  {
    id: "gen4",
    titleKey: "home.modes.gen4.title",
    descKey: "home.modes.gen4.desc",
    color: "bg-gray-900",
    Icon: Luxuryball,
  },
  {
    id: "gen5",
    titleKey: "home.modes.gen5.title",
    descKey: "home.modes.gen5.desc",
    color: "bg-slate-100",
    Icon: Premierball,
  },
  {
    id: "gen6",
    titleKey: "home.modes.gen6.title",
    descKey: "home.modes.gen6.desc",
    color: "bg-pink-400",
    Icon: Healball,
  },
  {
    id: "gen7",
    titleKey: "home.modes.gen7.title",
    descKey: "home.modes.gen7.desc",
    color: "bg-green-500",
    Icon: Nestball,
  },
  {
    id: "gen8",
    titleKey: "home.modes.gen8.title",
    descKey: "home.modes.gen8.desc",
    color: "bg-blue-800",
    Icon: Netball,
  },
  {
    id: "gen9",
    titleKey: "home.modes.gen9.title",
    descKey: "home.modes.gen9.desc",
    color: "bg-yellow-500",
    Icon: Quickball,
  },
  {
    id: "infinite",
    titleKey: "home.modes.infinite.title",
    descKey: "home.modes.infinite.desc",
    color: "bg-amber-600",
    Icon: InfiniteBall,
  },
];
